# FGDW002 - Fibaro Door Window Sensor 2
# https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/604
-   deviceName: FGDW002 - Fibaro Door Window Sensor 2
    manufacturerId: 271
    productTypeId: 1794
    groups:
    # send alarm
        1: 1
    config: 
        # bitmask:
        # 2_1 Visual LED indications - Open/close = 1; 
        # 2_2 Visual LED indications - wake up = 0;
        # 2_4 Visual LED indications - tampering = 0
        # -> 2 = 1
        2_1: 1
        # Interval of temperature measurements
        50_2: 0
        # Temperature reports threshold
        51_2: 0
        
-   deviceName: FGDW002 - Fibaro Door Window Sensor 1.5
    manufacturerId: 271
    productTypeId: 1793
    groups:
    # send alarm
        1: 1
    config: 
        # bitmask:
        # 2_1 Visual LED indications - Open/close = 1; 
        # 2_2 Visual LED indications - wake up = 0;
        # 2_4 Visual LED indications - tampering = 0
        # -> 2 = 1
        2_1: 1
        # Interval of temperature measurements
        50_2: 0
        # Temperature reports threshold
        51_2: 0

-   deviceName: FGDW002 - Fibaro Door Window Sensor 1
    manufacturerId: 271
    productTypeId: 1792
    groups:
    # send basic
        1: 1
    config: 
        # bitmask:
        # 2_1 Visual LED indications - Open/close = 1; 
        # 2_2 Visual LED indications - wake up = 0;
        # 2_4 Visual LED indications - tampering = 0
        # -> 2 = 1
        2_1: 1
        # Interval of temperature measurements
        50_2: 0
        # Temperature reports threshold
        51_2: 0

# ZW100 Multisensor 6 1.12
# https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/778
-   deviceName: ZW100 Multisensor 6
    manufacturerId: 134
    productTypeId: 2
    groups:
        1: 1
    config: 
        # factory reset
        #255_4: 1431655765
        # Motion Sensor reset timeout
        3_2: 10
        # Motion Sensor Triggered Command
        5_1: 2
        # sum of:
        # Battery=1
        # Ultraviolet=16
        # Temperature=32
        # Humidity=64
        # Light=128
        101_4: 97 
        # Group 1 Report Interval
        111_4: 3600

# FGWP102 Metered Wall Plug Switch
# https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/513
-   deviceName: FGWP102 Metered Wall Plug Switch
    manufacturerId: 271
    productTypeId: 1538
    groups:
        1: 1
        #2: 1
        #3: 1
    config:
        10_1: 90
        11_1: 100
        14_2: 0

# FGWP101 Metered Wall Plug Switch
# https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/130
-   deviceName: FGWP101 Metered Wall Plug Switch
    manufacturerId: 271
    productTypeId: 1536
    groups:
        1: 1
        #2: 1
        #3: 1
    config:
        10_1: 90
        11_1: 100
        14_2: 0

# FGBS001 Universal Binary Sensor
# https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/126
-   deviceName: FGBS001 Universal Binary Sensor
    manufacturerId: 271
    productTypeId: 1281
    groups:
        1: 1
        2: 1
        3: 1
        
# ZW139 Nano Switch Gen5 (without meter)
# https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/648
-   deviceName: ZW139 Nano Switch Gen5 (without meter)
    manufacturerId: 134
    productTypeId: 3
    groups:
        1: 1
        3: 1
    config:
        80_1: 2
        120_1: 0
        121_1: 0

# TPS412 Touch Panel Switch 2 Channel
# https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/429
-   deviceName: TPS412 Touch Panel Switch 2 Channel
    manufacturerId: 351
    productTypeId: 16673
    groups:
        1: 1
        2: 1
        3: 1

-   deviceName: BeNext Panic Watch
    manufacturerId: 138
    productTypeId: 21
    groups:
        1: 1
    config:
        4_1: 0        

-   deviceName: Fibaro Relais FGS-212
    manufacturerId: 271
    productTypeId: 1026
    groups:
        3: 1